declare module "@/*"
declare module "@/adapters/"
declare module "@/components/"
declare module "@/pages/*"
declare module "@/mocks/*"
declare module "@/models/*"
declare module "@/lib/*"
declare module "@/interceptors/*"